AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 162
  
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 30

Naming/PredicateName:
  AllowedMethods:
    - is_supported?

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20
